# Generated by Django 4.2.2 on 2023-07-03 20:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plots', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parcel',
            new_name='Plot',
        ),
    ]
